web:
  build: ./app
  volumes:
    - "./app:/src/app"
  ports:
    - "3030:3000"
  links:
    - mongo
  command: nodemon -L app/bin/www
  # command: [npm, "start"]
mongo:
  image: mongo
  ports:
  - "27017:27017"
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web
